export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface VideoMetadata {
  title: string;
  author: string;
  thumbnailUrl: string;
}

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface KeyTakeaway {
  point: string;
  description: string;
}

export interface Chapter {
  seconds: number;
  timeLabel: string;
  title: string;
  summary: string;
}

export interface MindmapNode {
  label: string;
  children?: MindmapNode[];
}

export interface VideoSummary {
  title: string;
  overallSummary: string;
  keyTakeaways: KeyTakeaway[];
  chapters: Chapter[];
  mindmap: MindmapNode;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: number;
}

export interface ProcessedVideo {
  videoId: string;
  title: string;
  author: string;
  thumbnailUrl: string;
  captionTracks: CaptionTrack[];
  selectedLanguage: string;
  transcript: TranscriptSegment[];
  summary: VideoSummary | null;
  notes: string;
  chatHistory: ChatMessage[];
  lastAccessed: number;
}
